### ISSUE TITLE
Roadmap: known issues and coming new features

### ISSUE THREAD

**Issue by itchyny** [itchyny/bed#1]
Thank you for getting interested in my product.

Notes:

- This product is my hobby product. Please do not ask me when some features will be implemented. I will implement what I want when I need (mostly) on weekends.
- Your advice for new features are welcome. I'm not familiar with reverse-engineering, I'm not an expert of some binary file format.
- This project is open sourced. You can freely create a fork of the repository. I appreciate if you send me patches to improve features, fix some bugs and so on.

### Multi-platform distribution
- [x] ~Testing on TravisCI~
  - Test in GitHub Actions
- [x] Homebrew rule
- [x] Windows support
  - [x] Fix `panic: send on closed channel` on exit 316b04c25d846b4a0773831ffadec4eb9c89ef91
  - [x] Write fails with `Access is denied.`: disable overwrite on Windows for now fb381a71457c8abfe3c6cfe5fb5073849e782c12
  - [x] Make tests pass on Windows 1fdf7a533f501c5a71a564549ea7e3744236527c
  - [x] Test on AppVeyor e8df7d5cbe7b262f1abfcc580e932ac756cd6af9
- [x] Distribution from GitHub Releases

### Small bugs
- [x] Visual mode should accept count for key mappings 6ce206ce2850e8f274faa6c1ff4dab5e7fde4180
- [ ] Cursor position should be taken into account on switching between windows
- [ ] One key stroke is missing after process suspension on macOS (known issue of tcell)
- [x] Replace (r) should exit replace mode at once 1087bf9a57f6329b74c2b920f4a6b9615c32f56b

### New features and improvements
I will definitely fix or implement these features.

- [x] Yank, cut and paste: 1817e545777392d4320f907a4a2c2535cf05d84d c39eb953a93815c53f334bd24ee7e40dce9ed209 260b641ad49768c0f6b20b09146454bf1a56fdae
- [x] Delete bytes (x, X) should copy the deleted region 8c3f9620c0db3d21eb747a29707b8a49f706ec4f 5d278e2f40a17fe88b60f4c04fcfab1a79cb863e 3eded553410fe172fb27b13df7b81b8648fd0575
- [x] Alternative buffer switching f4f4a52b37198da993fc85b9512a790f3be89a1f 9d4a72e85e90b35cb82a40b26b512e91fdd1927b c2e62b892580cf3efb4f3380221c85dce7d23128 14c60c0b8c01eecec4d76e5daacf394f61d273dd
- [x] Search by bytes 2e929ee63244a59f013bbae136153fbda03a9711
- [x] Search in asynchronous loop ccab6b84bab0b353bb903a1b8aa036a21450e1f7.
- [ ] Bitwise editing
- [ ] Marks
- [ ] Registers
- [ ] Aborting write with c-c
- [x] Command flags (--version, --help, etc.) feb31e1124ede7a423fdf2f6720ec27a8047e9ee
- [ ] Command line history
- [ ] Mouse support
- [ ] Execute external command
- [x] Vendor tcell with dep e47daf1dd8576a5fe4048ce0a5df789ea06032a2
  - Migrated to Go modules

More commands 

- [x] zt, zz, zb de8947caa91a978b6895d054ac3ebb7985974d3d 27f14bfc22009ef3f6cb75281b9b637ddda9073d 0841ff7bc946681aebe79a865d3da9901d6415a4 c1cff0d4b47bec24e691d7f0d8183b6bd7cd29c9 342e972c19dd2dc07c98718d13e6845a36c7b9ee cb213edba738ec28dd89cfabd0ed2276ae061bdb
- [x] :enew command e0dcb7fdd1aa3c3b4fa0ccedb7c40173d30281a1
- [ ] :buffer/:ls command
- [ ] :below command
- [ ] :split/:vsplit commands
- [ ] :topleft/botright/... commands
- [ ] :only command
- [ ] :new/:vnew should accept count to open with the specific height/width

### More features
Please do not expect me to implement these features, but I'm interested in. I need some feedbacks.

- [ ] Help buffer (:help)
  - Embed markdown documents?
- [ ] Diff (:diffthis/:diffoff)
- [ ] File format inspector
  - Using debug/elf package?
  - It'll be tough to implement many kinds of binary file formats. But I think I have to support for executables at least. There are already many soft-wares so needs investigation.
  - I'm also interested in image formats.
- [ ] Support multiple text encodings
  - bed is a binary editor. Maybe supporting for analyzer of executables has higher priority than text encodings.
- [ ] Configuration
  - I think this product should provide the good defaults. I'm not sure which parts users may want to configure. Mappings, displayed formats, event hooks ...
- [ ] Plugin
  - I can't imagine what kind of plugin is required for binary editors. I need some investigation of other editors.
  - Also, I don't want to create a new scripting language. gRPC support?
- [ ] Tabs
  - I like the tab behavior of Vim. But I hear that many people like displaying buffers in tabs.
- [ ] Session restoration
- [ ] Macro and repeating
- [ ] GUI frontend or web-based UI
- [ ] Stdin support

**Comment by monouser7dig** [comment]
> I think I started coding for what I want before doing research on existing editors.

maybe compare bed to [bvi](http://bvi.sourceforge.net) for people who do no want "a bin editor written in go" but "a bin editor that works well for me"

**Comment by Kerrigan29a** [comment]
> * It'll be tough to implement many kinds of binary file formats. But I think I have to support forexecutables at least. There are already many soft-wares so needs investigation.
> * I'm also interested in image formats.

 Probably you could use [Kaitai](http://kaitai.io/) to parse the files
